#
# Configuration of Mapsync
#
# MapSync - Created by Mr.Coco, 2021
#

hooks: # Only the players with the build permission can create maps.
  griefprevention: false
  # Available types:[ "Access" (/at) , "Build" (/trust) , "Admin" (/pt)]
  permission_type: "Admin"
mapitem:
  lore: # The lore of map you want to add after sync.
    - ""
    - "&7UUID: %UUID%"
    - "&7Author: %AUTHOR%"

message:
  already-sync: "&6[MapSync] &7This map is already synchronized."
  success-sync: "&6[MapSync] &aThis map is successfully synchronized!"
  no-permission: "&6[MapSync] &cYou do not have the require permission in this claim to open a new map."
