name: MapSync
version: ${project.version}
main: me.coco0325.mapsync.MapSync
api-version: 1.16
authors: [coco0325]
softdepend: [GriefPrevention, MysqlPlayerDataBridge]
description: Sync map items between multiple servers.

permissions:
  mapsync.use:
    description: Can create sync maps.
    default: op
